export const DEFAULT_USER_SETTINGS = {
  id: "default",
  userId: "guest",
  buyAmount: 0.5,
  maxBuyPerToken: 2.0,
  slippage: 10.0,
  autoTrade: false,
  minMarketCap: 0,
  maxMarketCap: 10000000,
  minHolders: 0,
  minLiquidity: 0,
  takeProfit: 50,
  stopLoss: 25,
  trailingStop: false,
  autoSellMinutes: 0,
  volumeSpikeEnabled: true,
  volumeSpikeThreshold: 50,
  whaleAlertEnabled: true,
  whaleWalletAddresses: [],
  dexBoostEnabled: true,
  dexListingEnabled: true,
  sources: ["Raydium", "Jupiter"],
  selectedBoostLevel: "Top Boost",
};
