export const DEFAULT_USER_SETTINGS = {
  id: "default",
  userId: "guest",
  buyAmount: 0.5,
  maxBuyPerToken: 2.0,
  slippage: 10.0,
  autoTrade: false,
  minMarketCap: 0,
  maxMarketCap: 0,
  minHolders: 1,
  minLiquidity: 0,
  takeProfit: 50,
  stopLoss: 25,
  trailingStop: false,
  autoSellMinutes: 0,
  dexBoostEnabled: true,
  dexListingEnabled: true,
  sources: ["Raydium", "Jupiter", "Pump.fun", "Meteora", "Orca"],
  selectedBoostLevel: "all",
  alertsEnabled: true,
  isPremium: false,
  dailyAlertCount: 0,
  lastAlertReset: new Date(),
};

export const FREE_DAILY_ALERT_LIMIT = 50;
